package eftaios.view;

import eftaios.model.events.ConnectedToGameEvent;
import eftaios.model.events.EndGameEvent;
import eftaios.model.events.EndOfTurnEvent;
import eftaios.model.events.GameStartedEvent;
import eftaios.model.events.GreenEscapePodEvent;
import eftaios.model.events.IOErrorEvent;
import eftaios.model.events.IllegalActionEvent;
import eftaios.model.events.IllegalPlayerEvent;
import eftaios.model.events.ItemRequestEvent;
import eftaios.model.events.LogPrintEvent;
import eftaios.model.events.NoiseInAnySectorEvent;
import eftaios.model.events.NoiseInYourSectorEvent;
import eftaios.model.events.RedEscapePodEvent;
import eftaios.model.events.SilenceEvent;
import eftaios.model.events.StartPlayerTurnEvent;
import eftaios.model.events.SuccessfulAttackEvent;
import eftaios.model.events.SuccessfulGivenItemListEvent;
import eftaios.model.events.SuccessfulItemAdditionEvent;
import eftaios.model.events.SuccessfulMoveOnDangerousSectorEvent;
import eftaios.model.events.SuccessfulMoveOnEscapePodSectorEvent;
import eftaios.model.events.SuccessfulMoveOnSafeSectorEvent;
import eftaios.model.events.SuccessfulMoveOnStartingSectorEvent;
import eftaios.model.events.SuccessfulMoveOnWallSectorEvent;
import eftaios.model.events.SuccessfulUseOfItemEvent;
import eftaios.model.events.SuccessfulUseOfSpotLightItemEvent;
import eftaios.model.events.TooMuchItemsEvent;
import eftaios.model.events.UnableToAttackEvent;

public interface EventVisitor {
    public void visitEvent(EndOfTurnEvent event);
    public void visitEvent(EndGameEvent event);
    public void visitEvent(GameStartedEvent event);
    public void visitEvent(GreenEscapePodEvent event);
    public void visitEvent(IllegalActionEvent event);
    public void visitEvent(IllegalPlayerEvent event);
    public void visitEvent(IOErrorEvent event);
    public void visitEvent(ItemRequestEvent event);
    public void visitEvent(LogPrintEvent event);
    public void visitEvent(NoiseInAnySectorEvent event);
    public void visitEvent(NoiseInYourSectorEvent event);
    public void visitEvent(RedEscapePodEvent event);
    public void visitEvent(SilenceEvent event);
    public void visitEvent(StartPlayerTurnEvent event);
    public void visitEvent(SuccessfulAttackEvent event);
    public void visitEvent(SuccessfulGivenItemListEvent event);
    public void visitEvent(SuccessfulItemAdditionEvent event);
    public void visitEvent(SuccessfulMoveOnDangerousSectorEvent event);
    public void visitEvent(SuccessfulMoveOnEscapePodSectorEvent event);
    public void visitEvent(SuccessfulMoveOnSafeSectorEvent event);
    public void visitEvent(SuccessfulMoveOnStartingSectorEvent event);
    public void visitEvent(SuccessfulMoveOnWallSectorEvent event);
    public void visitEvent(SuccessfulUseOfItemEvent event);
    public void visitEvent(SuccessfulUseOfSpotLightItemEvent event);
    public void visitEvent(TooMuchItemsEvent event);
    public void visitEvent(UnableToAttackEvent event);
    public void visitEvent(ConnectedToGameEvent connectedToGameEvent);
}
